import React, { useState } from 'react';
import Head from "next/head";
import { auth } from './firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useRouter } from 'next/navigation';
import Button from '@/components/Button';

const Home = () => {
  const [user, setUser] = useAuthState(auth);
  const router = useRouter();
  const [form, setForm] = useState({
    text: "",
  });

  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const signOut = () => {
    auth.signOut();
    router.push('/');
  }

  const generateImg = async () => {
    try {
      setGeneratingImg(true);
      console.log("Getting response from OpenAI...");
      const response = await fetch("/api/create", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      });

      const data = await response.json();
      console.log(data.text);
      setForm({ ...form, text: data.text })
    } catch (error) {
      alert(error);
    } finally {
      setGeneratingImg(false);
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (form.text) {
      setLoading(true);
      try {
        const response = await fetch("/api/create", {
          method: "POST",
          header: {
            accept: "application/json",
          },
          body: JSON.stringify(form),
        });
        await response.json();
        alert("Success");
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    } else {
      alert("Could not generate meme.")
    }
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? (
        <div>
          <header className='bg-slate-300'>
            <nav className='flex justify-between items-center mx-4'>
              <h2 className='text-white text-xl'>NextJS App</h2>
              <Button
                handleClick={signOut}
                text='SignOut'
              />
            </nav>
          </header>
          <main className='m-20'>
            <h1 className='font-bold uppercase text-3xl'>Create</h1>
            <div className='flex flex-col justify-between'>
              <div className='my-12'>
                <Button
                  handleClick={generateImg}
                  text='CREATE'
                />
              </div>
              <div>
                {form.text && (
                  <h1>{form.text}</h1>
                )}
                {generatingImg && (
                  <h1 className='font-bold uppercase text-xl'>Loading...</h1>
                )}
              </div>
              <div className='my-12'>
                <Button
                  handleClick={handleSubmit}
                  text='SAVE'
                />
              </div>
            </div>
          </main>
        </div>
      ) : (
        <div className='m-20'>
          <h1 className='font-bold uppercase text-3xl'>User not found</h1>
        </div>
      )}
    </>
  )
}

export default Home