import Head from "next/head";
import { auth } from './firebase';
import { useEffect } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import Login from '@/components/Login';

export default function Home() {
  const [user, setUser] = useAuthState(auth);

  useEffect(() => {
    console.log(user);
  }, [user])

  return (
    <>
      <Head>
        <title>Next.js & OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-200'>
        <Login />
      </main>
    </>
  )
}
